### ISSUE TITLE
Attempted to extract file modpack-slug-1.0.zip, but it did not exist

### ISSUE THREAD

**Issue by klahssik** [TechnicPack/TechnicSolder#421] opened 2015-07-24 01:14 UTC
SOMEONE PLEASE HELP IDK WHATS GOING ON I GET THIS MESSAGE PLZZZ HELLP!!!!!
 
Error unzipping a file for the following pack: KlahKi Craft 

Atempting to extract file klahki-craft-1.0.zip, but it did not exist. 

Please consult the modpack author 

PLZZZ HELP

**Comment by spannerman79** [comment] 2015-07-24 03:14
Close, dupe of #422

**Closed** 2015-07-24 16:46 UTC
