### ISSUE TITLE
 500  could not find driver

### ISSUE THREAD

**Issue by nikkimas** [TechnicPack/TechnicSolder#334] opened 2015-03-05 15:36 UTC
Hello,
I got it installed but when I login, I get redirected to an error Page.

http://puu.sh/gnvMm/26c42f0132.png

Did I forgot any Permission based issues?

**Comment by GibbsFrance** [comment] 2015-03-06 09:01
Hi,

I think your server does not have the driver that made the connection between PHP and a database.

If you use the default database, ensure that you have the php5-sqlite package if you are on a server that uses apt (debian / ubuntu). If you have changed the configuration to use mysql, check the installation of php5-mysql package.

Have a nice day.

**Comment by nikkimas** [comment] 2015-03-06 13:03
okay, I installed these. Then I wanted to reinstall Solder. But now this pops up if I run "composer install --no-dev --no-interaction"

![](http://puu.sh/goLkV/f38b35337a.png)


Is it my Server being weird or am I just stupid?

**Comment by GibbsFrance** [comment] 2015-03-06 15:44
It's not your server or you, it would seem fair that a dependency no longer available (HTTP/1.1 404 not found).  Try a little later, and if it does not work clean the directory and retry the installation.

**Comment by nikkimas** [comment] 2015-03-06 16:24
still not working. Is there any chance this will get fixed? (I tried reinstalling in differint dirs several times now)

**Comment by GibbsFrance** [comment] 2015-03-06 16:32
Since this is a problem that was not related to Technic but one of its dependencies, and that I am not a developer of this project, I can not give estimation on the time needed to fix this problem.

I will continue to look to my side if this problem is solved and will post a message if this is the case.

**Comment by nikkimas** [comment] 2015-03-06 16:51
okay, tank you :)

**Comment by GibbsFrance** [comment] 2015-03-06 17:38
After checking dependency, it seems that the team name was changed (https://github.com/borisrepl/boris/). This dependency is not used by the project directly but by Laravel version 4.2. I do not know how this will be fixed by Laravel, I'll try to find a workaround for now.

**Comment by GibbsFrance** [comment] 2015-03-07 07:32
Hi,

Lidbetter found a workaround for the problem (see [here](https://github.com/borisrepl/boris/issues/97#issuecomment-77574714)). Here is a [composer.json file](https://gist.github.com/GibbsFrance/93bc7acb302976ae65bb) that you can use instead of the one who is in the Technic Solder folder.

You just have to replace with it and resume the installation in step `composer install --no-dev --no-interaction`.

Have a nice day !

**Comment by TheDoctorsLife** [comment] 2015-03-07 14:40
@GibbsFrance Might be an idea to make a pull request to the repo so that other people can install solder.

**Comment by GibbsFrance** [comment] 2015-03-07 17:12
As indicated in the pull request, the bug is solved, it is no longer necessary to make the change of composer.json file. Hoping that everything goes well for you now :)

**Comment by nikkimas** [comment] 2015-03-09 15:31
Hi, unfortunately I saw your replies just now. I tried several times reinstalling Solder, and the install works, but when I open it in browser I get "Error in exception handler.". I tried using "chmod -R 775 solder/" but that didn't work either. I followed exactly these instructions "http://docs.solder.io/v0.7/docs/getting-started" but it just does not work :/

**Comment by GibbsFrance** [comment] 2015-03-09 15:37
Hi,

Check user and group owner of your installation (in Unix with ls -l). Your
Web Server do not be in the group and therefore the chmod is not effective.

**Comment by nikkimas** [comment] 2015-03-09 16:50
sorry, but I don't get what you mean(sorry my english is not very good)

**Comment by GibbsFrance** [comment] 2015-03-09 16:54
Same for me :)

If you have a Unix system (Linux or mac),  the command ls -l show list of
files with owner, group, date of creation... Do you can take a screenshot
and link in your reply and write what is your Web Server ? (apache,
Nginx,...)

**Comment by nikkimas** [comment] 2015-03-09 16:59
I'm on Debain 7 Wheezy. Apache2.  

![](http://puu.sh/gtdXn/0e131d27de.png)

**Comment by GibbsFrance** [comment] 2015-03-09 17:04
ok so if you read one line you can see "root root". It is because you clone TechnicSolder with root user. Apache2 use group www-data for permission. So run the command `chgrp -R www-data solder/` and after rerun chmod -R 755 solder/.

If this does not work, try creating a user and putting it in the group www-data.

**Comment by nikkimas** [comment] 2015-03-09 17:35
Okay, thank you! It finally works :D Now I have to find out how to use Solder^^. Thanks for your help!

**Comment by GibbsFrance** [comment] 2015-03-09 17:36
It was a pleasure :)

**Comment by nikkimas** [comment] 2015-03-09 19:03
okay, I think I broke it!
![](http://puu.sh/gtn8C/c87843611a.png)

I didn't delete the textures. Do I may have to alter the permissions for them them seperatly?

**Comment by GibbsFrance** [comment] 2015-03-09 19:07
I do not think it is a permissions problem here.

Try to refresh the page by emptying your browser cache. It can also be a slow internet connection which cancels the query "design files".

**Comment by nikkimas** [comment] 2015-03-09 19:10
Not only I have the Problem. go on http://solder.macoga.de/ it just does not work for us with textures (solder does not like me :D)

**Comment by GibbsFrance** [comment] 2015-03-09 19:17
Apparently your version does not contain some files.

![capture](https://cloud.githubusercontent.com/assets/1565272/6562423/58f4fd64-c699-11e4-95ac-419c010225d1.PNG)

My login.css is in solder/public/css folder. Check if exists and as the case we will seek the right solution.

**Comment by nikkimas** [comment] 2015-03-09 19:21
![](http://puu.sh/gtoyf/49d9bea205.png)


wrenchIcon.svg is not there

**Comment by GibbsFrance** [comment] 2015-03-09 19:26
Because it is in another folder :)  but if you have login.css, it's not the problem of missing files. What is your configuration of Apache ? (in particular for this domain name / VirtualHost)

**Comment by nikkimas** [comment] 2015-03-09 19:28
<VirtualHost *:80>
	ServerAlias solder.macoga.de
	DocumentRoot /var/www/solder/public/index.php
</VirtualHost>

**Comment by GibbsFrance** [comment] 2015-03-09 19:32
Ok, I just tried your configuration, and the problem is that you add /index.php to DocumentRoot visibly.

**Comment by nikkimas** [comment] 2015-03-09 19:38
okay, it works now, but http://solder.macoga.de/ is now not working. I have to add /index.php. Is there a way I don't have to do it?

**Comment by TheDoctorsLife** [comment] 2015-03-09 19:39
http://solder.macoga.de/index.php/login use this

**Comment by GibbsFrance** [comment] 2015-03-09 19:41
May be a documentation on rewrite is necessary because it's been several people who have this problem ^^

**Comment by TheDoctorsLife** [comment] 2015-03-09 19:42
Suggest an edit on the docs

**Comment by nikkimas** [comment] 2015-03-09 19:48
I knew I have to add /index.php ^^ but the question is, why was it working before with the other apache2 settings?

**Comment by GibbsFrance** [comment] 2015-03-09 19:53
Because when you set DocumentRoot with /index.php, it redirects all requests to this adress, but it is not good because DocumentRoot must be a folder and not a file, otherwise it causes errors like about graphic files.

**Comment by nikkimas** [comment] 2015-03-09 19:55
I know, but it worked for about half an hour and then suddenly didn't work anymore

**Comment by GibbsFrance** [comment] 2015-03-09 19:59
It's a good question, I don't know why graphics file is send to you with the old configuration before.

**Comment by nikkimas** [comment] 2015-03-11 19:50
Okay, I created now a pack via Solder, linked it to my account, but when I click install this shows up: "The modpack XXX does not appear to be installed or is corrupt, and is not available for Offline Play."

Even though I think Imade all the files correctly.

**Comment by GibbsFrance** [comment] 2015-03-11 19:53
Hi,

Check issue #338, I think it can help you :)

**Comment by nikkimas** [comment] 2015-03-12 11:39
Okay, stupid haven't looked at closed issues, hehe. It works now, BUT, the next Problem is there D: (I feel very stupid right now). When I have (according to this: http://docs.solder.io/v0.7/docs/zip-file-structure) the structure right, it wont download. But when I have e.g.: just renamed the .jar to .zip it downloads (but obviosly not it isnt installed right).

**Comment by GibbsFrance** [comment] 2015-03-12 11:42
What do you want to say with "it wont download"? Bad URL, not install ? Can
you send a link of mod in your repository with right structure ?

**Comment by nikkimas** [comment] 2015-03-12 11:48
http://solder.macoga.de/mods/mods/appliedenergistics2/  the .zip is the one that wont download, the .zip1 is the one that downloads (I always change the .zipX to test stuff)

**Comment by GibbsFrance** [comment] 2015-03-12 11:51
The zip is correct. May be you have add it to Solder before the upload is complete. Go to your mod page in your Solder and click the "Rehash" button next to the corresponding version.

**Comment by nikkimas** [comment] 2015-03-12 12:00
okay, that works. I forgot it's saving it with the md5 thing. Thank you :D

**Comment by GibbsFrance** [comment] 2015-03-12 17:25
No problem :) If you don't have more questions, please consider to close this ticket.

**Closed** 2015-03-13 18:36 UTC
