### ISSUE TITLE
Rehash file bug in build: 0.7.2.2

### ISSUE THREAD

**Issue by Dockter** [TechnicPack/TechnicSolder#469] opened 2015-09-28 02:09 UTC
When I attempt to rehash a file within Solder, I get this:

MD5 hashing complete. MD5 provided does not match file MD5: e6640364fd6ff0f47327b2306196841f

If I copy the e6640364fd6ff0f47327b2306196841f and put it in the textbox to the left of the filename and click "rehash" again, it accepts the updated file

"MD5 hashing complete."

Thoughts?

**Comment by mcsnetworks** [comment] 2015-09-28 02:12
Genpage has access to this solder server:  solder.almuramc.com

**Comment by GenPage** [comment] 2015-09-29 02:27
So this issue is an effect of the new manual MD5 entry feature. The logic of this is a bit flawed and will need some better implementation to avoid the issues I'm currently seeing starting to pop up from dev users.

Current Logic:
* if the md5 input is empty, set the MD5 from file.
* if the md5 input is not empty, set the MD5 from input
  * if md5 input != md5 from file or md5 from file is null, prompt warning but still set MD5 from input
  * if md5 input == md5 from file, success

The problem with this logic is that the previous md5 stored is set in the input on page load automatically, so when you "rehash" using a new file, the MD5s will of course be different.
 
(see https://github.com/TechnicPack/TechnicSolder/blob/master/app/views/mod/view.blade.php#L107)

Some discussion about better logic would be appreciated, mainly how to handle the UI aspect of new/old MD5s with the manual input

**Comment by Isigiel** [comment] 2016-04-02 10:57
I think, there should be the input field, filled with the current vaue, leaving the behaviour, if nothing is supplied
Next to the input, an update button, which will save the current value directly, and then an option to paste the current calculated md5 into the input
So it's very clear, whatever is in the field gets saved, but you have an option to use the auto-hashing

(Discord copy)

**Comment by Pyker** [comment] 2020-05-21 23:12
I'm closing this as a likely duplicate of https://github.com/TechnicPack/TechnicSolder/issues/545.

**Closed by Pyker** 2020-05-21 23:12 UTC
Labels: Priority: High, Status: Needs Feedback, Type: Bug
