### ISSUE TITLE
error: internal Server Error after trying to add mod

### ISSUE THREAD

**Issue by evilarceus** [TechnicPack/TechnicSolder#544] opened 2016-01-17 08:55 UTC
(feeling this doesn't have to be a problem with Solder itself, but help is appreciated)

When I try to add Forge to the mod list, it says there's an internal server error.
My repo and mirror url are set to "/home/evilarceus/Desktop/repo/". I'm assuming it's a problem from there. Here's the structure I have:

-mods
--forgeloader
---forgeloader-1563.zip

Everything is set to unrestricted permissions in those files/folders.

Help would be appreciated!

**Comment by LemADEC** [comment] 2016-01-17 18:11
Your mirror repository URL is the publicly accessible link for clients to download your mods, hence it should start with http://xxxx. If that's the case, ensure your mods zip are actually accessible from http://

**Comment by evilarceus** [comment] 2016-01-17 18:26
Ok, changed it to http://mattuweb.x10host.com/solder/repo/mods/forgeloader/forgeloader-1563.zip and it still comes up with the same error. If I were to go to that link, it downloads it fine in my browser. Is there any error log I can see?

**Comment by LemADEC** [comment] 2016-01-17 18:35
Check your apache logs

**Comment by evilarceus** [comment] 2016-01-17 18:38
I use Nginx. Should I switch to Apache?

(nginx logs have nothing in them)

**Comment by LemADEC** [comment] 2016-01-17 19:35
Up to you

**Comment by spannerman79** [comment] 2016-01-17 23:29
Move hosts - https://github.com/TechnicPack/TechnicSolder/issues/240#issuecomment-69517064

**Comment by Aaesos** [comment] 2016-02-27 11:58
Change your Solder installation into debug mode, as it will give you some useful information.

If inside the log file at .../app/storage/logs/ it says anything concerning
`General error: 1 table modversions has no column named filesize`
then you are having the same problem as I am.

For unknown reasons, Solder decided to add support for mod filesizes, however by default, solder SQLITE databases don't come with a filesize column.

There are two ways to fix this. Either you can edit the SQLITE database and insert the required "filesize" column into the modversions.

The easier way is to use a MySQL database, as Solder will properly add the filesize column.

**Comment by SyriusTank** [comment] 2016-03-02 05:02
Added the column to the modversions table, fixed the issue.

**Comment by GenPage** [comment] 2016-03-29 01:53
Duplicate of #523. Closing

**Closed by GenPage** 2016-03-29 01:53 UTC
