### ISSUE TITLE
URLs with \/ (http://:x/modrepo\/mods\/...)

### ISSUE THREAD

**Issue by GeARCraft1** [TechnicPack/TechnicSolder#442] opened 2015-08-26 18:55 UTC
Hi Again!
I installed solder and now the api is returning the urls with \/.
Example: background":"http:\/\/191.188.125.206:8999\/resources\/default\/background.jpg
Can you help me please??

**Comment by Indemnity83** [comment] 2015-08-26 19:04
Duplicate of #441 and cross post of #434 

There is no need to post multiple times for the same question...

**Comment by Indemnity83** [comment] 2015-08-26 19:57
After looking into this, the '\/' is still completely valid [JSON](http://json.org/) and is the correct behavior here even if it doesn't look pretty. 

Is it causing issues with the launcher? If it is, it's technically a bug with the launcher although it could be fixed in TechnicSolder if there is a desire to make it look pretty using the [JSON_UNESCAPED_UNICODE ](http://www.php.net/manual/en/json.constants.php#constant.json-unescaped-slashes) constant on the Response::json line, but I would recommend against it.

**Comment by Pyker** [comment] 2015-09-10 20:41
This is not a bug. The API is returning perfectly valid JSON that any decent JSON parser can handle.

**Closed** 2015-09-10 22:32 UTC
