### ISSUE TITLE
ErrorException messages when performing initial install - MAMP install

### ISSUE THREAD

**Issue by ChipCustomizer** [TechnicPack/TechnicSolder#584] opened 2016-06-14 01:41 UTC
I have a MAMP install (Mac, Apache, MySQL and PHP).  I was able to get through most of the setups, but when I perform the step below I get ErrorExceptions.  I can't seem to figure out what's going wrong here.  Can anyone help?

Specs:
OSX 10.11.5
PHP 5.6.11

Daniels-iMac:TechnicSolder Dan$ composer install --no-dev --no-interaction
Cannot create cache directory /Users/Dan/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /Users/Dan/.composer/cache/files/, or directory is not writable. Proceeding without cache
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating autoload files
> php -r "shell_exec((strtoupper(substr(PHP_OS, 0, 3)) === 'WIN') ? 'mkdir app\config && copy app\config-sample app\config' : 'cp -r app/config-sample app/config');"
> php -r "copy('app/database-sample/production.sqlite', 'app/database/production.sqlite');"
> php -r "chmod('app/storage', 0775);"
> php -r "chmod('public/resources', 0775);"
> php artisan clear-compiled
{"error":{"type":"ErrorException","message":"date_default_timezone_set(): Timezone ID 'PST' is invalid","file":"\/Users\/Dan\/TechnicSolder\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/start.php","line":167}}> php artisan optimize
{"error":{"type":"ErrorException","message":"date_default_timezone_set(): Timezone ID 'PST' is invalid","file":"\/Users\/Dan\/TechnicSolder\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/start.php","line":167}}> php artisan key:generate
{"error":{"type":"ErrorException","message":"date_default_timezone_set(): Timezone ID 'PST' is invalid","file":"\/Users\/Dan\/TechnicSolder\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/start.php","line":167}}Daniels-iMac:TechnicSolder

**Comment by skwerlman** [comment] 2016-06-14 05:24
Could you put the console output in triple backticks for readability?

    ```
    (output here)
    ```

**Comment by ChipCustomizer** [comment] 2016-06-14 05:31
```
Daniels-iMac:TechnicSolder Dan$ composer install --no-dev --no-interaction
Cannot create cache directory /Users/Dan/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /Users/Dan/.composer/cache/files/, or directory is not writable. Proceeding without cache
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating autoload files
> php -r "shell_exec((strtoupper(substr(PHP_OS, 0, 3)) === 'WIN') ? 'mkdir app\config && copy app\config-sample app\config' : 'cp -r app/config-sample app/config');"
> php -r "copy('app/database-sample/production.sqlite', 'app/database/production.sqlite');"
> php -r "chmod('app/storage', 0775);"
> php -r "chmod('public/resources', 0775);"
> php artisan clear-compiled
{"error":{"type":"ErrorException","message":"date_default_timezone_set(): Timezone ID 'PST' is invalid","file":"\/Users\/Dan\/TechnicSolder\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/start.php","line":167}}> php artisan optimize
{"error":{"type":"ErrorException","message":"date_default_timezone_set(): Timezone ID 'PST' is invalid","file":"\/Users\/Dan\/TechnicSolder\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/start.php","line":167}}> php artisan key:generate
{"error":{"type":"ErrorException","message":"date_default_timezone_set(): Timezone ID 'PST' is invalid","file":"\/Users\/Dan\/TechnicSolder\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/start.php","line":167}}Daniels-iMac:TechnicSolder
```

**Comment by SquidDoctor** [comment] 2016-06-21 10:13
Also getting the same error in a different enviornment:
 - OS: Fedora 23 (4.4.3-300, 64bit)
 - LEMP Stack
   - PHP 5.6.19 (64bit)
   - Nginx 1.9.9 (64bit)
   - MySQL (MariaDB 10.0.23, 32bit)
 - Composer (local installation, 1.1.2)

Running composer install as root.

**Comment by skwerlman** [comment] 2016-06-21 19:20
This is similar to the error we've been having in CI (for all versions: https://travis-ci.org/TechnicPack/TechnicSolder) for a while. I looked into it a while back but couldn't find anything substantial. Maybe someone with better google-fu than I can figure this out...

/cc @GenPage

**Comment by daemonnecis** [comment] 2016-07-06 23:14
I had the same problem but could solve it.
First make sure you have ALL mentioned PHP mods. Take a double check.

The cause of the problem is problably, that for some reason composer post script refuses to copy ```"app/config-sample/"``` to ```"app/config"```. You have to do it manually.
After that edit "app/config/app.php" and fill in your timezone.
Then run composers post script commands again:
```
php artisan clear-compiled                                                                                                                                                                                     
php artisan optimize
```

**Comment by daemonnecis** [comment] 2016-07-06 23:17
Maybe we could find a better title for that issue for documentational reason.

**Comment by skwerlman** [comment] 2016-07-06 23:23
@daemonnecis Thanks for looking into this. Feel free to suggest an edit on docs.solder.io if you want to improve documentation.

I'm gonna check whether this helps with travis, and maybe open a pr

**Comment by skwerlman** [comment] 2016-07-09 07:49
@ChipCustomizer did @daemonnecis's solution work for you? If so, can you close this ticket?

**Comment by ChipCustomizer** [comment] 2016-07-17 05:49
It looks like it may have worked - I'm not seeing the error.  I did have to set the timezone to "America/Los_Angeles" since it didn't take PST or PDT as a timezone.  Maybe EST doesn't work either and that's the problem?  EST should be "America/New_York" maybe?  I'll continue the install and see if I can get forward now.  Thanks for the help - here is my output:
```
Daniels-iMac:TechnicSolder Dan$ php artisan clear-compiled
Daniels-iMac:TechnicSolder Dan$ php artisan optimize
Generating optimized class loader
Compiling common classes
Compiling views
Daniels-iMac:TechnicSolder Dan$ composer install --no-dev --no-interaction
Cannot create cache directory /Users/Dan/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /Users/Dan/.composer/cache/files/, or directory is not writable. Proceeding without cache
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating autoload files
> php -r "shell_exec((strtoupper(substr(PHP_OS, 0, 3)) === 'WIN') ? 'mkdir app\config && copy app\config-sample app\config' : 'cp -r app/config-sample app/config');"
> php -r "copy('app/database-sample/production.sqlite', 'app/database/production.sqlite');"
> php -r "chmod('app/storage', 0775);"
> php -r "chmod('public/resources', 0775);"
> php artisan clear-compiled
> php artisan optimize
Generating optimized class loader
Compiling common classes
Compiling views
> php artisan key:generate
Application key [UouNW1xDMVHjxXjdfHXFJYhzwARCCrev] set successfully.
Daniels-iMac:TechnicSolder Dan$ 
```

**Comment by skwerlman** [comment] 2016-07-17 09:28
Log looks good; if you're not seeing the error any longer, could you close this ticket?

**Closed** 2016-07-17 16:46 UTC
