### ISSUE TITLE
HTTPS Doesn't work?

### ISSUE THREAD

**Issue by tankerkiller125** [TechnicPack/TechnicSolder#560] opened 2016-03-01 12:19 UTC
I have set the app/config/app.php to use https://solder.rhodes.ml but the css and links still are using http is there away to fix this easily?

**Comment by skwerlman** [comment] 2016-03-01 21:14
dup of #554, fixed by #556, please close

**Comment by tankerkiller125** [comment] 2016-03-02 12:43
Cloudflare should be doing the 301 Redirects. But apparently Firefox doesn't like to follow HTTP at all if its served from a HTTPS URL

**Comment by tankerkiller125** [comment] 2016-03-02 13:04
I've fixed the problem by manually going through and updating all the assets tags (and `URL::to()`) into the secure versions (like `asset('/path/to/asset.js', true)`)

**Comment by skwerlman** [comment] 2016-03-03 00:03
Cloudflare doesn't handle redirects, it just passes them through to the client. In my case, I didn't need to edit any actual PHP, just OpenSans.css... Perhaps the issue is with your server configuration?

Which server are you using, and would you mind sharing the relevant bits of the config?

**Closed** 2016-03-13 20:42 UTC
