### ISSUE TITLE
'Add Mod To Modpack' list problem

### ISSUE THREAD

**Issue by Ionaru** [TechnicPack/TechnicSolder#499] opened 2015-12-06 22:44 UTC
When in the Build Management menu, the list that expands when selecting a new mod for the modpack stays inside its box and only shows a very small section of the list.
This also happens when selecting a version for that new mod.

The 'Add Mod To Modpack' box then becomes scrollable.

See the pictures for more detail.

![screenshot 2015-12-06 23 30 40](https://cloud.githubusercontent.com/assets/3472373/11616104/51937b80-9c73-11e5-97ed-36fa21511485.png)

![screenshot 2015-12-06 23 30 50](https://cloud.githubusercontent.com/assets/3472373/11616105/56a3587a-9c73-11e5-924a-be45fd3b592a.png)

![screenshot 2015-12-06 23 31 50](https://cloud.githubusercontent.com/assets/3472373/11616106/5919e6aa-9c73-11e5-827c-b351ee121567.png)

**Comment by EntranceJew** [comment] 2015-12-07 00:37
This was caused by #430 setting overflow settings for the panels. This can be mitigated by having the overflow settings only apply to x and disable them for y. I can have a fix for this tomorrow.

**Closed** 2015-12-08 16:15 UTC
Labels: bug, minor
